[package]
name = "taffy-clib"
version = "0.1.0"
edition = "2021"

[dependencies]
stretch2 = { version = "0.4.2" }

[lib]
name = "taffy"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

